SimpleFleetManagement/SimpleFleetManagement/Controllers/FleetController.cs
using SimpleFleetManagement.DataAccess;
using SimpleFleetManagement.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SimpleFleetManagement.Controllers
{
    public class FleetController : Controller
    {
        // GET: Fleet
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult List()
        {
            List<FleetViewModel> model = FleetDataAccess.GetAll();
            return View(model);
        }
               
        public ActionResult Create()
        {
            ViewBag.KaroseriList = new SelectList(KaroseriDataAccess.GetAll(), "KaroseriId", "Description");
            ViewBag.MerkBusList = new SelectList(MerkBusDataAccess.GetAll(), "MerkId", "Description");
            ViewBag.TypeBusList = new SelectList(TypeBusDataAccess.GetByMerkBus(""), "TypeId", "Description");
            return View();
        }

        public ActionResult Edit(int id)
        {
            FleetViewModel model = FleetDataAccess.GetById(id);
            ViewBag.KaroseriList = new SelectList(KaroseriDataAccess.GetAll(), "KaroseriId", "Description");
            ViewBag.MerkBusList = new SelectList(MerkBusDataAccess.GetAll(), "MerkId", "Description");
            ViewBag.TypeBusList = new SelectList(TypeBusDataAccess.GetByMerkBus(model.MerkId), "TypeId", "Description");
            return View(model);
        }

        public ActionResult Delete(int id)
        {
            return View(FleetDataAccess.GetById(id));
        }

        // POST: Fleet
        [HttpPost]
        public ActionResult Create(FleetViewModel model)
        {
            return CreateEdit(model);
        }

        [HttpPost]
        public ActionResult Edit(FleetViewModel model)
        {
            return CreateEdit(model);
        }

        [HttpPost]
        public ActionResult DeleteConf(int id)
        {
            if (FleetDataAccess.Delete(id))
            {
                return Json(new { success = true, Message = "Delete Success" }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new { success = false, Message = "Error" }, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult CreateEdit(FleetViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (FleetDataAccess.Update(model))
                    {
                        return Json(new { success = true, Message = "Success" }, JsonRequestBehavior.AllowGet);
                    }
                    else
                    {
                        return Json(new { success = false, Message = FleetDataAccess.Message }, JsonRequestBehavior.AllowGet);
                    }
                }
                else
                {
                    return Json(new { success = false, Message = "Please complete all required field" }, JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception Ex)
            {
                return Json(new { success = false, Message = Ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }
    }
}

SimpleFleetManagement/SimpleFleetManagement/Controllers/MaintenanceController.cs
using SimpleFleetManagement.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SimpleFleetManagement.Controllers
{
    public class MaintenanceController : Controller
    {
        // GET: Maintenance
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult MaintenanceHeaderForm()
        {
            return View();
        }

        public ActionResult MaintenanceList()
        {
            List<MaintenanceDetailViewModel> model = new List<MaintenanceDetailViewModel>();
            return View(model);
        }

        //[HttpPost]
        //public ActionResult SaveMaintenance(MaintenanceHeaderViewModel model)
        //{
        //    try
        //    {
        //        if (ModelState.IsValid)
        //        {

        //        }
        //    }
        //}
    }
}

SimpleFleetManagement/SimpleFleetManagement/Views/Maintenance/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@*<h2>Maintenance</h2>*@

<div class="panel-group">
    <div class="panel panel-default">
        <div class="panel-heading">
            <div class="row">
                <div class="col-md-9">
                    <button type="button" id="btn-new" class="btn btn-twitter" title="New Transaction" onclick="window.location.href='@Url.Action("Index","Maintenance")'">
                        <span class="fa fa-shopping-cart" aria-hidden="true"></span>
                        Add Maintenance
                    </button>
                </div>
                <div class="col-lg-3">
                    Refference Code : <span id="reference-code">-</span>
                </div>
            </div>
            <br />
            <div class="row">
                <div class="col-md-3">
                    <input id="txt-search" type="text" class="form-control" placeholder="Search" />
                </div>
                <div class="col-md-6">
                    <button type="button" id="btn-add" class="btn btn-search" title="Search Fleet">
                        <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                        Search Fleet
                    </button>
                </div>
            </div>
        </div>
        <div class="panel-body">
            <div id="maintenance info">
                @Html.Partial("MaintenanceHeaderForm")
            </div>
        </div>
    </div>
</div>

<div id="modal-form" class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-lg" role="document">
        <div class="panel-group">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <h4 class="modal-title">@ViewBag.Title</h4>
                </div>
                <div class="modal-body panel-body">

                </div>
            </div>
        </div>
    </div>
</div>

@*//nanti ini diedit ya*@ 

@*<div class="panel-group">
    <div class="panel panel-default">
        <div class="panel-heading">
            <button type="button" class="btn btn-primary btn-add-salarycomponent">Add Item</button>
            <button type="button" class="btn btn-success btn-save-salarycomponent">Save Selling</button>
        </div>
        <div class="selling-list">
            @Html.Action("SellingList", "Selling")
        </div>
    </div>
</div>*@

@section Scripts
{
    <script type="text/javascript">
        $('.datepicker').datepicker({ format: "dd M yyyy" });

        $(".btn-search").click(function () {
            SelectFleet($('#txt-search').val());
        });

        function SelectFleet(fleetid) {
            //alert("jalan woe");
            $.ajax({
                url: '@Url.Action("GetFleetByFleetId", "Fleet")',
                type: 'get',
                data: { fleetid: fleetid },
                success: function (result) {
                    if (result.success) {
                        var f = result.data;
                        //$("#MaintenanceId").val();
                        //$("#MaintenanceDate").val();
                        $("#FleetId").val(f.FleetId);
                        $("#BrandTypeName").val(f.BrandTypeName);
                        $("#LicenseNumber").val(f.LicenseNumber);
                        //$("#MaintenanceKm").val();
                    }
                    else {
                        FleetList();
                    }
                }
            });
        }

        function FleetList() {
            $.ajax({
                url: '@Url.Action("GetByFilter", "Fleet")',
                data: { filterstring: $('#txt-search').val() },
                type: 'get',
                success: function (result) {
                    $(".modal-body").html(result);
                    $(".modal-title").html("Select Fleet");
                    $("#modal-form").modal('show');
                }
            });
        }

        @*$('.btn-add-item').click(function () {
            //alert($("#BadgeId").val().length);
            if ($("#MaintenanceId").val().length > 0) {
                var itemlist = [''];
                $("input[name=ItemCode]").each(function () {
                    itemlist.push($(this).val());
                });
                //alert(itemlist);
                $.ajax({
                    url: '@Url.Action("ExceptList", "Item")',
                    data: { exceptlist: itemlist },
                    type: 'get',
                    traditional: true,
                    success: function (result) {
                        $(".modal-body").html(result);
                        $(".modal-title").html("Add an Item");
                        $("#modal-form").modal('show');
                    }
                });
            } else {
                alert("No Employee Selected");
            }
});*@

    </script>
    }

SimpleFleetManagement/SimpleFleetManagement/Views/Maintenance/MaintenanceHeaderForm.cshtml
@model SimpleFleetManagement.ViewModel.MaintenanceHeaderViewModel


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">        
        @*@Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.MaintenanceId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaintenanceId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaintenanceId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaintenanceDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaintenanceDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaintenanceDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FleetId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FleetId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FleetId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaintenanceKm, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaintenanceKm, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaintenanceKm, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TotalPrice, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TotalPrice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TotalPrice, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>*@
    
    <div class="form-group">
        <label class="control-label col-md-2" for="MaintenanceId">Maintenance Id</label>
        <div class="col-md-10">
            <input class="form-control text-box single-line" data-val="true" data-val-required="Harus diisi ya" id="MaintenanceId" name="MaintenanceId" @*readonly="readonly" type="text" value=""*@>
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-2" for="MaintenanceDate">Maintenance Date</label>
        <div class="col-md-10">
            <input class="form-control text-box single-line datepicker" id="MaintenanceDate" name="MaintenanceDate" readonly="readonly" type="text" value="@DateTime.Now.ToString("dd MMM yyyy")">
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-2" for="FleetId">Fleet Id</label>
        <div class="col-md-10">
            <input class="form-control text-box single-line" data-val="true" data-val-required="Harus diisi ya" id="FleetId" name="FleetId" readonly="readonly" type="text" value="">
        </div>
    </div>

        <div class="form-group">
            <label class="control-label col-md-2" for="BrandTypeName">Brand Type Name</label>
            <div class="col-md-10">
                <input class="form-control text-box single-line" data-val="true" data-val-required="Harus diisi ya" id="BrandTypeName" name="BrandTypeName" readonly="readonly" type="text" value="">
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2" for="LicenseNumber">License Number</label>
            <div class="col-md-10">
                <input class="form-control text-box single-line" data-val="true" data-val-required="Harus diisi ya" id="LicenseNumber" name="LicenseNumber" readonly="readonly" type="text" value="">
            </div>
        </div>

    <div class="form-group">
        <label class="control-label col-md-2" for="MaintenanceKm">Maintenance KM</label>
        <div class="col-md-10">
            <input class="form-control text-box single-line" data-val="true" data-val-required="Harus diisi ya" id="MaintenanceKm" name="MaintenanceKm" @*readonly="readonly" type="text" value=""*@>
        </div>
    </div>

    <div class="col-lg-offset-2">
        <h1>Total : <span id="selling-total">0.00</span></h1>
    </div>
 </div>   
}

<script type="text/javascript">

</script>