SimpleFleetManagement/SimpleFleetManagement/Controllers/CustomerController.cs
using SimpleFleetManagement.DataAccess;
using SimpleFleetManagement.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SimpleFleetManagement.Controllers
{
    public class CustomerController : Controller
    {
        // GET: Customer
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult List()
        {
            List<CustomerViewModel> model = CustomerDataAccess.GetAll();
            return View(model);
        }
        
        public ActionResult GetByCustomerId(string customerid)
        {
            CustomerViewModel model = CustomerDataAccess.GetByCustomerId(customerid);
            if (model != null)
            {
                return Json(new { success = true, data = model }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new { success = false, JsonRequestBehavior.AllowGet }, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult GetByFilter(string filterstring)
        {
            return View(CustomerDataAccess.GetByFilter(filterstring));
        }

        public ActionResult Create()
        {
            return View();
        }

        public ActionResult Edit(int id)
        {
            return View(CustomerDataAccess.GetById(id));
        }

        public ActionResult Delete(int id)
        {
            return View(CustomerDataAccess.GetById(id));
        }

        // POST: Customer
        [HttpPost]
        public ActionResult Create(CustomerViewModel model)
        {
            return CreateEdit(model);
        }

        [HttpPost]
        public ActionResult Edit(CustomerViewModel model)
        {
            return CreateEdit(model);
        }

        [HttpPost]
        public ActionResult DeleteConf(int id)
        {
            if (CustomerDataAccess.Delete(id))
            {
                return Json(new { success = true, Message = "Delete Success" }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new { success = false, Message = "Error" }, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult CreateEdit(CustomerViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (CustomerDataAccess.Update(model))
                    {
                        return Json(new { success = true, Message = "Success" }, JsonRequestBehavior.AllowGet);
                    }
                    else
                    {
                        return Json(new { success = false, Message = CustomerDataAccess.Message }, JsonRequestBehavior.AllowGet);
                    }
                }
                else
                {
                    return Json(new { success = false, Message = "Please complete all required field" }, JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception Ex)
            {
                return Json(new { success = false, Message = Ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }
    }
}

SimpleFleetManagement/SimpleFleetManagement/Controllers/OrderController.cs
using SimpleFleetManagement.DataAccess;
using SimpleFleetManagement.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SimpleFleetManagement.Controllers
{
    public class OrderController : Controller
    {
        // GET: Order
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult OrderForm()
        {
            return View();
        }

        public ActionResult FleetOrderList()
        {
            List<FleetOrderViewModel> models = new List<FleetOrderViewModel>();
            return View(models);
        }

        [HttpPost]
        public ActionResult FleetOrderItem(FleetOrderViewModel model)
        {
            return View(model);
        }

        public ActionResult AddFleetOrderItem(/*FleetOrderException fleetorderexception*/List<string> fleetexceptlistVal, List<string> driverexceptlistVal, List<string> assistantexceptlistVal, string startdateVal, string enddateVal)
        {
            FleetOrderException fleetorderexception = new FleetOrderException
            {
                fleetexceptlist = fleetexceptlistVal,
                driverexceptlist = driverexceptlistVal,
                assistantexceptlist = assistantexceptlistVal,
                startdate = startdateVal,
                enddate = enddateVal
            };


            ViewBag.FleetExceptList = FleetDataAccess.GetByFleetException(fleetorderexception).Select(flt => new SelectListItem
            {
                Value = flt.FleetId,
                Text = flt.FleetId + " " + flt.LicenseNumber + " " + flt.BrandTypeName
            });

            ViewBag.DriverExceptList = new SelectList(CrewDataAccess.GetByDriverException(fleetorderexception), "CrewId", "CrewName");

            ViewBag.AssistantExceptList = new SelectList(CrewDataAccess.GetByAssistantException(fleetorderexception), "CrewId", "CrewName");

            ViewBag.StartDate = fleetorderexception.startdate;

            ViewBag.EndDate = fleetorderexception.enddate;
            
            return View();
        }
    }
}

SimpleFleetManagement/SimpleFleetManagement/Views/Order/AddFleetOrderItem.cshtml
@model SimpleFleetManagement.ViewModel.FleetOrderViewModel

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.FleetId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.FleetId, (IEnumerable<SelectListItem>)ViewBag.FleetExceptList, "Select Fleet", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.FleetId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DriverId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.DriverId, (IEnumerable<SelectListItem>)ViewBag.DriverExceptList, "Select Driver", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.DriverId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AssitantId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.AssitantId, (IEnumerable<SelectListItem>)ViewBag.AssistantExceptList, "Select Assistant", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.AssitantId, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="modal-footer">
                <input type="button" value="Add to Fleet Order List" class="btn btn-success btn-add-busorder" />
                <input type="button" value="Cancel" class="btn btn-default" data-dismiss="modal" />
        </div>
    </div>
}
<script type="text/javascript">
    $(".btn-add-busorder").click(function () {
        var item = {
            FleetId: $("#FleetId").val(),
            FleetName: $("#FleetId option:selected").text(),
            DriverId: $("#DriverId").val(),
            DriverName: $("#DriverId option:selected").text(),
            AssitantId: $("#AssitantId").val(),
            AssitantName: $("#AssitantId option:selected").text()
        };
        //alert(JSON.stringify(item));
        AddFleetOrderItem(item);
})
    </script>

SimpleFleetManagement/SimpleFleetManagement/Views/Order/FleetOrderItem.cshtml
@model SimpleFleetManagement.ViewModel.FleetOrderViewModel

<tr>
    <td>
        @Html.EditorFor(model => model.FleetId, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } }) 
        <br />
        @Html.EditorFor(model => model.FleetName, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
    </td>

    <td>
        @Html.EditorFor(model => model.DriverId, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
        <br />
        @Html.EditorFor(model => model.DriverName, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
    </td>

    <td>
        @Html.EditorFor(model => model.AssitantId, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
        <br />
        @Html.EditorFor(model => model.AssitantName, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
    </td>
       
    <td>
        <button type="button" class="btn btn-danger btn-remove" onclick="RemoveItem(this)">Remove</button>
    </td>
</tr>

SimpleFleetManagement/SimpleFleetManagement/Views/Order/FleetOrderList.cshtml
@model IEnumerable<SimpleFleetManagement.ViewModel.FleetOrderViewModel>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FleetId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DriverId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AssitantId)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody class="fleet-order-list">
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.FleetId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DriverId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.AssitantId)
                </td>
            </tr>
        }
</table>

SimpleFleetManagement/SimpleFleetManagement/Views/Order/Index.cshtml
@{
    ViewBag.Title = "New Order";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="panel-group">
    <div class="panel panel-default">
        <div class="panel-heading">
            <div class="row">
                <div class="col-md-9">
                    <button type="button" id="btn-new" class="btn btn-twitter" title="New Order" onclick="window.location.href='@Url.Action("Index","Order")'">
                        <span class="fa fa-shopping-cart" aria-hidden="true"></span>
                        New Order
                    </button>
                </div>
            </div>
        </div>
        <div class="panel-body">
            <div class="form-group">
                <div class="col-md-3">
                    <input id="txt-search" type="text" class="form-control" placeholder="Search" />
                </div>
                <div class="col-md-2">
                    <button type="button" id="btn-add" class="btn btn-search" title="Search Customer">
                        <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                        Search Customer
                    </button>
                </div>
                <div class="col-md-2">
                    <button type="button" id="btn-add-customer" class="btn btn-success btn-add-customer" title="Add New Customer">
                        Add New Customer
                    </button>
                </div>
            </div>
        </div>
        <div class="panel-body">
            <div id="employee info">
                @Html.Partial("OrderForm")
            </div>
        </div>
        <div class="panel-heading">
            <button type="button" class="btn btn-primary btn-add-fleetorder">Add Fleet</button>
            <button type="button" class="btn btn-success btn-save-order">Save Order</button>
        </div>
        <div>
            @Html.Action("FleetOrderList", "Order")
        </div>
    </div>
</div>

<div id="modal-form" class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-lg" role="document">
        <div class="panel-group">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <h4 class="modal-title">@ViewBag.Title</h4>
                </div>
                <div class="modal-body panel-body">

                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts
{
    <script type="text/javascript">
    $('.datepicker').datepicker({ format: "dd M yyyy" });

    $('#txt-search').keypress(function (e) {
        if (e.keyCode == 13)
            $('.btn-search').click();
    });

    //////////// CUSTOMER AND ORDER ZONE ////////////////

    $(".btn-add-customer").click(function () {
        //to be added
    });

    $(".btn-search").click(function () {
        SelectCustomer($('#txt-search').val());
    });

    function SelectCustomer(customerid) {
        $.ajax({
            url: '@Url.Action("GetByCustomerId", "Customer")',
            type: 'get',
            data: { customerid: customerid },
            success: function (result) {
                if (result.success) {
                    var ctm = result.data;
                    $("#CustomerId").val(ctm.CustomerId);
                    $("#CustomerName").val(ctm.CustomerName + " (" + ctm.OrganizationName + ")");
                }
                else {
                    CustomerList();
                }
            }
        });
    }

    function CustomerList() {
        $.ajax({
            url: '@Url.Action("GetByFilter", "Customer")',
            data: { filterstring: $('#txt-search').val() },
            type: 'get',
            success: function (result) {
                $(".modal-body").html(result);
                $(".modal-title").html("Select Customer");
                $("#modal-form").modal('show');
            }
        });
    }

    //////////// BUS ORDER ZONE ////////////////

    $('.btn-add-fleetorder').click(function () {
              
        if (($("#CustomerId").val().length > 0) &&
            ($("#StartDate").val().length > 0) &&
            ($("#EndDate").val().length > 0)) {

            
            var fleetexceptList = [''];
            $("input[name=FleetId]").each(function () {
                fleetexceptList.push($(this).val());
            });

            var driverexceptList = [''];
            $("input[name=DriverId]").each(function () {
                driverexceptList.push($(this).val());
            });

            var assistantexceptList = [''];
            $("input[name=AssitantId]").each(function () {
                assistantexceptList.push($(this).val());
            });

            var startDate = $("#StartDate").val();
            var endDate = $("#EndDate").val();

            var item = {
                fleetexceptlist: fleetexceptList,
                driverexceptlist: driverexceptList,
                assistantexceptlist: assistantexceptList,
                startdate: startDate,
                enddate: endDate
            };
            //alert(JSON.stringify(item));
            $.ajax({
                url: '@Url.Action("AddFleetOrderItem", "Order")',
                type: 'get',
                traditional: true,
                data: { //fleetorderexception: item
                    fleetexceptlistVal: fleetexceptList,
                    driverexceptlistVal: driverexceptList,
                    assistantexceptlistVal: assistantexceptList,
                    startdateVal: startDate,
                    enddateVal: endDate
                },
                success: function (result) {
                    $(".modal-body").html(result);
                    $(".modal-title").html("Add Fleet Order");
                    $("#modal-form").modal('show');
                }
            });
        } else {
            alert("Please complete all fields");
        }
    });

        function AddFleetOrderItem(item) {
        //alert(JSON.stringify(item));
        $.ajax({
            url: '@Url.Action("FleetOrderItem", "Order")',
            type: 'post',
            data: { model: item },
            success: function (result) {
                if (result) {
                    $("#modal-form").modal("hide");
                    $(".fleet-order-list").append(result)
                } else {
                    alert('Error : ' + result.Message);
                }
            }
        });
    }

    function RemoveItem(obj) {
        //$(obj).closest('tr').remove();
        var description = 'Bus ' + $(obj).closest('tr').find('input[name=FleetName]').val();
        var remove = confirm("Are you sure to remove " + description + " ?");
        if (remove) {
            $(obj).closest('tr').remove();
        }
    }

    </script>
}

SimpleFleetManagement/SimpleFleetManagement/Views/Order/OrderForm.cshtml
@model SimpleFleetManagement.ViewModel.OrderViewModel

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.OrderId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.OrderId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OrderId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CustomerId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CustomerId, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.CustomerId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CustomerName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CustomerName, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.CustomerName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OrderName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.OrderName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OrderName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OrderDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.OrderDate, new { htmlAttributes = new { @class = "form-control datepicker", @Value = DateTime.Now.ToString("dd MMM yyyy") } })
                @Html.ValidationMessageFor(model => model.OrderDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Destination, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Destination, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Destination, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control datepicker" } })
                @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EndDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { @class = "form-control datepicker" } })
                @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TotalPerson, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TotalPerson, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TotalPerson, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>
}