SimpleFleetManagement/SimpleFleetManagement/Controllers/KaroseriController.cs
using SimpleFleetManagement.DataAccess;
using SimpleFleetManagement.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SimpleFleetManagement.Controllers
{
    public class KaroseriController : Controller
    {
        // GET: Karoseri
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult List()
        {
            List<KaroseriViewModel> model = KaroseriDataAccess.GetAll();
            return View(model);
        }

        public ActionResult Create()
        {
            return View();
        }

        public ActionResult Edit(int id)
        {
            return View(KaroseriDataAccess.GetById(id));
        }

        public ActionResult Delete(int id)
        {
            return View(KaroseriDataAccess.GetById(id));
        }

        // POST: Karoseri
        [HttpPost]
        public ActionResult Create(KaroseriViewModel model)
        {
            return CreateEdit(model);
        }

        [HttpPost]
        public ActionResult Edit(KaroseriViewModel model)
        {
            return CreateEdit(model);
        }

        [HttpPost]
        public ActionResult DeleteConf(int id)
        {
            if (KaroseriDataAccess.Delete(id))
            {
                return Json(new { success = true, Message = "Delete Success" }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new { success = false, Message = "Error" }, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult CreateEdit(KaroseriViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (KaroseriDataAccess.Update(model))
                    {
                        return Json(new { success = true, Message = "Success" }, JsonRequestBehavior.AllowGet);
                    }
                    else
                    {
                        return Json(new { success = false, Message = KaroseriDataAccess.Message }, JsonRequestBehavior.AllowGet);
                    }
                }
                else
                {
                    return Json(new { success = false, Message = "Please complete all required field" }, JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception Ex)
            {
                return Json(new { success = false, Message = Ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }
    }
}

SimpleFleetManagement/SimpleFleetManagement/Views/Karoseri/Create.cshtml
@model SimpleFleetManagement.ViewModel.KaroseriViewModel

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.KaroseriId, htmlAttributes: new { @class = "control-label col-md-3" })
            <div class="col-md-9">
                @Html.EditorFor(model => model.KaroseriId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.KaroseriId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-3" })
            <div class="col-md-9">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label col-md-3" })
            <div id="checkbox" class="col-md-9">
                <div>
                    @Html.EditorFor(model => model.IsActive)
                    @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        
        <div class="modal-footer">
                <input type="button" value="Create" class="btn btn-success btn-create-conf" />
                <input type="button" value="Cancel" class="btn btn-default" data-dismiss="modal" />
        </div>
    </div>
}

<script type="text/javascript">
    $(".btn-create-conf").click(function () {
        var item = {
            id: 0,
            KaroseriId: $("#KaroseriId").val(),
            Description: $("#Description").val(),
            IsActive: $("#IsActive").is(":checked")
        };
        //alert(JSON.stringify(item));
        $.ajax({
            url: '@Url.Action("Create","Karoseri")',
            type: 'post',
            data: {model:item},
            success: function(result){
                if(result.success){
                    $("#modal-form").modal("hide");
                    ShowList();
                } else {
                    alert('Error : '+result.Message);
                }
            }
        });
    })
</script>

SimpleFleetManagement/SimpleFleetManagement/Views/Karoseri/Delete.cshtml
@model SimpleFleetManagement.ViewModel.KaroseriViewModel

<h3>Are you sure you want to delete this?</h3>
<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.KaroseriId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.KaroseriId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsActive)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsActive)
        </dd>
        
    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="modal-footer">
            <input type="button" value="Delete" class="btn btn-danger btn-delete-conf" data-id="@Model.Id" />
            <input type="button" value="Cancel" class="btn btn-default" data-dismiss="modal" />
        </div>
    }
</div>

<script type="text/javascript">
    $(".btn-delete-conf").click(function () {
        //alert('Idnya adalah : ' + $(this).attr('data-id'));
        $.ajax({
            url: '@Url.Action("DeleteConf","Karoseri")',
            type: 'post',
            data: { id: $(this).attr('data-id') },
            success: function (result) {
                if (result.success) {
                    $("#modal-form").modal("hide");
                    ShowList();
                }
                else {
                    alert('Error: ' + result.Message);
                }
            }
        });
    });
</script>

SimpleFleetManagement/SimpleFleetManagement/Views/Karoseri/Edit.cshtml
@model SimpleFleetManagement.ViewModel.KaroseriViewModel

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.KaroseriId, htmlAttributes: new { @class = "control-label col-md-3" })
            <div class="col-md-9">
                @Html.EditorFor(model => model.KaroseriId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.KaroseriId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-3" })
            <div class="col-md-9">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label col-md-3" })
            <div id="checkbox" class="col-md-9">
                <div>
                    @Html.EditorFor(model => model.IsActive)
                    @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="modal-footer">
                <input type="button" value="Save Changes" class="btn btn-warning btn-edit-conf" />
                <input type="button" value="Cancel" class="btn btn-default" data-dismiss="modal" />
        </div>
    </div>
}

<script type="text/javascript">
    $(".btn-edit-conf").click(function () {
        var item = {
            id: $("#Id").val(),
            KaroseriId: $("#KaroseriId").val(),
            Description: $("#Description").val(),
            IsActive: $("#IsActive").is(":checked")
        };
        //alert(JSON.stringify(item));
        $.ajax({
            url: '@Url.Action("Edit","Karoseri")',
            type: 'post',
            data: { model: item },
            success: function (result) {
                if (result.success) {
                    $("#modal-form").modal("hide");
                    ShowList();
                } else {
                    alert('Error : ' + result.Message);
                }
            }
        });
    });
</script>

SimpleFleetManagement/SimpleFleetManagement/Views/Karoseri/Index.cshtml
@{
    ViewBag.Title = "Karoseri";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@Styles.Render("~/AdminLTE/plugins/datatables/css")


<div class="panel-group">
    <div class="panel panel-default">
        <div class="panel-heading">
            <button type="button" id="btn-add" class="btn btn-success" title="Create New">
                <span class="glyphicon glyphicon-book" aria-hidden="true"></span>
                Create New
            </button>
        </div>
        <div class="panel-body">
            <div id="table-list">
                @*<div class="progress progress-striped active" style="margin-bottom:0"><div class="progress-bar"style="width:100%"/></div>*@
            </div>
        </div>
    </div>
</div>

@*<div class="row">
        <div class="col-lg-12">

        </div>
    </div>

    <br />

    <div class="row">
        <div class="col-lg-12">
            <div id="table-list">Loading...</div>
        </div>
    </div>*@

<div id="modal-form" class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="panel-group">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <h4 class="modal-title">@ViewBag.Title</h4>
                </div>
                <div class="modal-body panel-body">
                    <p>Modal body text goes here.</p>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts
    {
    <script type="text/javascript">

            var progHtml = '<div class="progress progress-striped active" style="margin-bottom:0"><div class="progress-bar"style="width:100%"/></div>';

        $(document).ready(function(){
            ShowList();
        })

        function ShowList() {
            $("#table-list").html(progHtml);
            $.ajax({
                url: '@Url.Action("List","Karoseri")',
                type: 'get',
                success: function (result) {
                    $("#table-list").html(result);
                }
            });
        }
        $("#btn-add").click(function () {
            $.ajax({
                url: '@Url.Action("Create","Karoseri")',
                type: 'get',
                success: function (result) {
                    $(".modal-body").html(result);
                    $(".modal-title").html("Add Karoseri")
                    $("#modal-form").modal("show");
                }
            });

            //alert($("#toggle1").is(":checked"));
        });
        //$('#btn-tgl').click(function () {
        //    $('.toggle').toggleClass('btn-info btn-default');
        //});
    </script>
}

SimpleFleetManagement/SimpleFleetManagement/Views/Karoseri/List.cshtml
@model IEnumerable<SimpleFleetManagement.ViewModel.KaroseriViewModel>

<table id="data-list" class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.KaroseriId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IsActive)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.KaroseriId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.IsActive)
                </td>
                <td>
                    <input type="button" value="Edit" class="btn btn-warning btn-edit" data-id="@item.Id" />
                    <input type="button" value="Delete" class="btn btn-danger btn-delete" data-id="@item.Id" />
                </td>
            </tr>
        }
    </tbody>
</table>

@Scripts.Render("~/AdminLTE/plugins/datatables/js")

<script type="text/javascript">
    $("#data-list").DataTable({
        "paging": true,
        "lengthChange": true,
        "searching": true,
        "ordering": true,
        "info": true,
        "autoWidth": false
    });

    $(".btn-edit").click(function () {
        //alert('Idnya adalah : ' + $(this).attr("data-id"));
        $.ajax({
            url: '@Url.Action("Edit","Karoseri")',
            type: 'get',
            data: { id: $(this).attr("data-id") },
            success: function (result) {
                $(".modal-body").html(result);
                $(".modal-title").html("Edit Department")
                $("#modal-form").modal("show");
            }
        });
    });

    $(".btn-delete").click(function () {
        //alert('Idnya adalah : ' + $(this).attr("data-id"));
        $.ajax({
            url: '@Url.Action("Delete","Karoseri")',
            type: 'get',
            data: { id: $(this).attr("data-id") },
            success: function (result) {
                $(".modal-body").html(result);
                $(".modal-title").html("Delete Karoseri")
                $("#modal-form").modal("show");
            }
        });
    });
</script>