SimpleFleetManagement/SimpleFleetManagement/Controllers/FleetController.cs
using SimpleFleetManagement.DataAccess;
using SimpleFleetManagement.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SimpleFleetManagement.Controllers
{
    public class FleetController : Controller
    {
        // GET: Fleet
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult List()
        {
            List<FleetViewModel> model = FleetDataAccess.GetAll();
            return View(model);
        }
               
        public ActionResult Create()
        {
            ViewBag.KaroseriList = new SelectList(KaroseriDataAccess.GetAll(), "KaroseriId", "Description");
            ViewBag.MerkBusList = new SelectList(MerkBusDataAccess.GetAll(), "MerkId", "Description");
            ViewBag.TypeBusList = new SelectList(TypeBusDataAccess.GetByMerkBus(""), "TypeId", "Description");
            return View();
        }

        public ActionResult Edit(int id)
        {
            FleetViewModel model = FleetDataAccess.GetById(id);
            ViewBag.KaroseriList = new SelectList(KaroseriDataAccess.GetAll(), "KaroseriId", "Description");
            ViewBag.MerkBusList = new SelectList(MerkBusDataAccess.GetAll(), "MerkId", "Description");
            ViewBag.TypeBusList = new SelectList(TypeBusDataAccess.GetByMerkBus(model.MerkId), "TypeId", "Description");
            return View(model);
        }

        public ActionResult Delete(int id)
        {
            return View(FleetDataAccess.GetById(id));
        }

        // POST: Fleet
        [HttpPost]
        public ActionResult Create(FleetViewModel model)
        {
            return CreateEdit(model);
        }

        [HttpPost]
        public ActionResult Edit(FleetViewModel model)
        {
            return CreateEdit(model);
        }

        [HttpPost]
        public ActionResult DeleteConf(int id)
        {
            if (FleetDataAccess.Delete(id))
            {
                return Json(new { success = true, Message = "Delete Success" }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new { success = false, Message = "Error" }, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult CreateEdit(FleetViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (FleetDataAccess.Update(model))
                    {
                        return Json(new { success = true, Message = "Success" }, JsonRequestBehavior.AllowGet);
                    }
                    else
                    {
                        return Json(new { success = false, Message = FleetDataAccess.Message }, JsonRequestBehavior.AllowGet);
                    }
                }
                else
                {
                    return Json(new { success = false, Message = "Please complete all required field" }, JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception Ex)
            {
                return Json(new { success = false, Message = Ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }
    }
}

SimpleFleetManagement/SimpleFleetManagement/Controllers/TypeBusController.cs
using SimpleFleetManagement.DataAccess;
using SimpleFleetManagement.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SimpleFleetManagement.Controllers
{
    public class TypeBusController : Controller
    {
        // GET: Type
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult List()
        {
            List<TypeBusViewModel> model = TypeBusDataAccess.GetAll();
            return View(model);
        }

        public ActionResult GetByMerkId(string merkid)
        {
            List<TypeBusViewModel> model = TypeBusDataAccess.GetByMerkBus(merkid);
            return View(model);
        }

        public ActionResult Create()
        {
            ViewBag.MerkBusList = new SelectList(MerkBusDataAccess.GetAll(), "MerkId", "Description");
            return View();
        }

        public ActionResult Edit (int id)
        {
            ViewBag.MerkBusList = new SelectList(MerkBusDataAccess.GetAll(), "MerkId", "Description");
            return View(TypeBusDataAccess.GetById(id));
        }

        [HttpPost]
        public ActionResult Create(TypeBusViewModel model)
        {
            return CreateEdit(model);
        }

        [HttpPost]
        public ActionResult Edit(TypeBusViewModel model)
        {
            return CreateEdit(model);
        }

        public ActionResult CreateEdit(TypeBusViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (TypeBusDataAccess.Update(model))
                    {
                        return Json(new { success = true, message = "Success" }, JsonRequestBehavior.AllowGet);
                    }
                    else
                    {
                        return Json(new { success = false, message = TypeBusDataAccess.Message }, JsonRequestBehavior.AllowGet);
                    }
                }
                else
                {
                    return Json(new { success = false, message = "Lengkapi isi form nya" }, JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception ex)
            {
                return Json(new { success = false, ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult Delete(int id)
        {
            return View(TypeBusDataAccess.GetById(id));
        }

        public ActionResult DeleteConfirm(int id)
        {
            if (TypeBusDataAccess.Delete(id))
            {
                return Json(new { success = true, message = "Success" }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new { success = false, message = TypeBusDataAccess.Message }, JsonRequestBehavior.AllowGet);
            }
            return Json(new { success = false, message = "Error :p" }, JsonRequestBehavior.AllowGet);

        }
    }
}

SimpleFleetManagement/SimpleFleetManagement/Views/Fleet/Create.cshtml
@model SimpleFleetManagement.ViewModel.FleetViewModel

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.FleetId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FleetId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FleetId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MerkName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.MerkId, (IEnumerable<SelectListItem>)ViewBag.MerkBusList, "Select Bus Brand", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TypeId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TypeName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.TypeId, (IEnumerable<SelectListItem>)ViewBag.TypeBusList, "Select Bus Type", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TypeId, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            @Html.LabelFor(model => model.LicenseNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LicenseNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LicenseNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.KaroseriId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.KaroseriId, (IEnumerable<SelectListItem>)ViewBag.KaroseriList, "Select Karoseri", new { @class = "form-control" })
                @*@Html.EditorFor(model => model.KaroseriId, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.ValidationMessageFor(model => model.KaroseriId, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            @Html.LabelFor(model => model.SeatCapacity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SeatCapacity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SeatCapacity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label col-md-2" })
            <div id="checkbox" class="col-md-9">
                <div>
                    @Html.EditorFor(model => model.IsActive)
                    @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        
        <div class="modal-footer">
                <input type="button" value="Create" class="btn btn-success btn-create-conf" />
                <input type="button" value="Cancel" class="btn btn-default" data-dismiss="modal" />
        </div>
    </div>
}

<script type="text/javascript">
    $('#MerkId').change(function () {
        //alert($('#MerkId').val());
        $.ajax({
            url: '@Url.Action("GetByMerkId","TypeBus")',
            type: 'get',
            data: { merkid: $(this).val() },
            success: function (result) {
                $("#TypeId").html(result);
            }
        });
    });

    $(".btn-create-conf").click(function () {
        var item = {
            id: 0,
            FleetId: $("#FleetId").val(),
            TypeId: $("#TypeId").val(),
            LicenseNumber: $("#LicenseNumber").val(),
            KaroseriId: $("#KaroseriId").val(),
            SeatCapacity: $("#SeatCapacity").val(),
            IsActive: $("#IsActive").is(":checked")
        };
        //alert(JSON.stringify(item));
        $.ajax({
            url: '@Url.Action("Create","Fleet")',
            type: 'post',
            data: { model: item },
            success: function (result) {
                if (result.success) {
                    $("#modal-form").modal("hide");
                    ShowList();
                } else {
                    alert('Error : ' + result.Message);
                }
            }
        });
    })
</script>

SimpleFleetManagement/SimpleFleetManagement/Views/Fleet/Delete.cshtml
@model SimpleFleetManagement.ViewModel.FleetViewModel

<h3>Are you sure you want to delete this?</h3>
<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FleetId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FleetId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TypeName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TypeName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LicenseNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LicenseNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.KaroseriName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.KaroseriName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SeatCapacity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SeatCapacity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsActive)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsActive)
        </dd>
        
    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="modal-footer">
            <input type="button" value="Delete" class="btn btn-danger btn-delete-conf" data-id="@Model.Id" />
            <input type="button" value="Cancel" class="btn btn-default" data-dismiss="modal" />
        </div>
    }
</div>

<script type="text/javascript">
    $(".btn-delete-conf").click(function () {
        //alert('Idnya adalah : ' + $(this).attr('data-id'));
        $.ajax({
            url: '@Url.Action("DeleteConf","Fleet")',
            type: 'post',
            data: { id: $(this).attr('data-id') },
            success: function (result) {
                if (result.success) {
                    $("#modal-form").modal("hide");
                    ShowList();
                }
                else {
                    alert('Error: ' + result.Message);
                }
            }
        });
    });
</script>

SimpleFleetManagement/SimpleFleetManagement/Views/Fleet/Edit.cshtml
@model SimpleFleetManagement.ViewModel.FleetViewModel

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.FleetId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FleetId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FleetId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MerkName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.MerkId, (IEnumerable<SelectListItem>)ViewBag.MerkBusList, "Select Bus Brand", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TypeId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TypeName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.TypeId, (IEnumerable<SelectListItem>)ViewBag.TypeBusList, "Select Bus Type", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TypeId, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            @Html.LabelFor(model => model.LicenseNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LicenseNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LicenseNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.KaroseriId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.KaroseriId, (IEnumerable<SelectListItem>)ViewBag.KaroseriList, "Select Karoseri", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.KaroseriId, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            @Html.LabelFor(model => model.SeatCapacity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SeatCapacity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SeatCapacity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label col-md-2" })
            <div id="checkbox" class="col-md-9">
                <div>
                    @Html.EditorFor(model => model.IsActive)
                    @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="modal-footer">
                <input type="button" value="Save Changes" class="btn btn-warning btn-edit-conf" />
                <input type="button" value="Cancel" class="btn btn-default" data-dismiss="modal" />
        </div>
    </div>
}

<script type="text/javascript">
    $('#MerkId').change(function () {
        //alert($('#MerkId').val());
        $.ajax({
            url: '@Url.Action("GetByMerkId","TypeBus")',
            type: 'get',
            data: { merkid: $(this).val() },
            success: function (result) {
                $("#TypeId").html(result);
            }
        });
    });

    $(".btn-edit-conf").click(function () {
        var item = {
            id: $("#Id").val(),
            FleetId: $("#FleetId").val(),
            TypeId: $("#TypeId").val(),
            LicenseNumber: $("#LicenseNumber").val(),
            KaroseriId: $("#KaroseriId").val(),
            SeatCapacity: $("#SeatCapacity").val(),
            IsActive: $("#IsActive").is(":checked")
        };
        //alert(JSON.stringify(item));
        $.ajax({
            url: '@Url.Action("Edit","Fleet")',
            type: 'post',
            data: { model: item },
            success: function (result) {
                if (result.success) {
                    $("#modal-form").modal("hide");
                    ShowList();
                } else {
                    alert('Error : ' + result.Message);
                }
            }
        });
    });
</script>

SimpleFleetManagement/SimpleFleetManagement/Views/Fleet/GetByFilter.cshtml
@model IEnumerable<SimpleFleetManagement.ViewModel.FleetViewModel>

<table id="data-list" class="table">
    <thead>
        <tr>
            <th>

            </th>
            <th>
                @Html.DisplayNameFor(model => model.FleetId)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.BrandTypeName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LicenseNumber)
            </th>
        </tr>
    </thead>

    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    <button type="button" class="btn btn-success btn-select-fleet" data-id="@item.Id" data-fleet="@item.FleetId" data-dismiss="modal">
                        Select
                    </button>
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FleetId)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.BrandTypeName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LicenseNumber)
                </td>

            </tr>
        }
    </tbody>

</table>

<script type="text/javascript">
    $('.btn-select-fleet').click(function () {
        SelectFleet($(this).attr("data-fleet"));
    });

</script>

SimpleFleetManagement/SimpleFleetManagement/Views/Fleet/Index.cshtml
@{
    ViewBag.Title = "Fleet";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@Styles.Render("~/AdminLTE/plugins/datatables/css")


<div class="panel-group">
    <div class="panel panel-default">
        <div class="panel-heading">
            <button type="button" id="btn-add" class="btn btn-success" title="Create New">
                <span class="glyphicon glyphicon-book" aria-hidden="true"></span>
                Create New
            </button>
        </div>
        <div class="panel-body">
            <div id="table-list">
                @*<div class="progress progress-striped active" style="margin-bottom:0"><div class="progress-bar"style="width:100%"/></div>*@
            </div>
        </div>
    </div>
</div>

@*<div class="row">
        <div class="col-lg-12">

        </div>
    </div>

    <br />

    <div class="row">
        <div class="col-lg-12">
            <div id="table-list">Loading...</div>
        </div>
    </div>*@

<div id="modal-form" class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-lg" role="document">
        <div class="panel-group">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <h4 class="modal-title">@ViewBag.Title</h4>
                </div>
                <div class="modal-body panel-body">
                    <p>Modal body text goes here.</p>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts
    {
    <script type="text/javascript">

            var progHtml = '<div class="progress progress-striped active" style="margin-bottom:0"><div class="progress-bar"style="width:100%"/></div>';

        $(document).ready(function(){
            ShowList();
        })

        function ShowList() {
            $("#table-list").html(progHtml);
            $.ajax({
                url: '@Url.Action("List","Fleet")',
                type: 'get',
                success: function (result) {
                    $("#table-list").html(result);
                }
            });
        }
        $("#btn-add").click(function () {
            $.ajax({
                url: '@Url.Action("Create","Fleet")',
                type: 'get',
                success: function (result) {
                    $(".modal-body").html(result);
                    $(".modal-title").html("Add Fleet")
                    $("#modal-form").modal("show");
                }
            });

            //alert($("#toggle1").is(":checked"));
        });
        //$('#btn-tgl').click(function () {
        //    $('.toggle').toggleClass('btn-info btn-default');
        //});
    </script>
}

SimpleFleetManagement/SimpleFleetManagement/Views/Fleet/List.cshtml
@model IEnumerable<SimpleFleetManagement.ViewModel.FleetViewModel>

<table id="data-list" class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FleetId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BrandTypeName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LicenseNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.KaroseriName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SeatCapacity)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IsActive)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.FleetId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.BrandTypeName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LicenseNumber)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.KaroseriName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SeatCapacity)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.IsActive)
                </td>
                <td>
                    <input type="button" value="Edit" class="btn btn-warning btn-edit" data-id="@item.Id" />
                    <input type="button" value="Delete" class="btn btn-danger btn-delete" data-id="@item.Id" />
                </td>
            </tr>
        }
    </tbody>
</table>

@Scripts.Render("~/AdminLTE/plugins/datatables/js")

<script type="text/javascript">
    $("#data-list").DataTable({
        "paging": true,
        "lengthChange": true,
        "searching": true,
        "ordering": true,
        "info": true,
        "autoWidth": false
    });

    $(".btn-edit").click(function () {
        //alert('Idnya adalah : ' + $(this).attr("data-id"));
        $.ajax({
            url: '@Url.Action("Edit","Fleet")',
            type: 'get',
            data: { id: $(this).attr("data-id") },
            success: function (result) {
                $(".modal-body").html(result);
                $(".modal-title").html("Edit Fleet")
                $("#modal-form").modal("show");
            }
        });
    });

    $(".btn-delete").click(function () {
        //alert('Idnya adalah : ' + $(this).attr("data-id"));
        $.ajax({
            url: '@Url.Action("Delete","Fleet")',
            type: 'get',
            data: { id: $(this).attr("data-id") },
            success: function (result) {
                $(".modal-body").html(result);
                $(".modal-title").html("Delete Fleet")
                $("#modal-form").modal("show");
            }
        });
    });
</script>